apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnettest
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/dotnettest:6daf7afe4e97291a405348dfd61a8b14b8bb90c9
        name: dotnettest
