apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnettest
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/dotnettest:8328ddacc4150c2ec7eea06a2ebff60b5184848d
        name: dotnettest
