apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: php-hello-event-listener
  namespace: tekton-tutorial
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-tag-php-hello
